[lint]
ignore = [
	"EM101",  # https://docs.astral.sh/ruff/rules/raw-string-in-exception
	"EM102",  # https://docs.astral.sh/ruff/rules/f-string-in-exception
	"FA",     # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
	"FBT001", # https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument
	"INP001", # https://docs.astral.sh/ruff/rules/implicit-namespace-package
	"N806",   # https://docs.astral.sh/ruff/rules/non-lowercase-variable-in-function
	"N818",   # https://docs.astral.sh/ruff/rules/error-suffix-on-exception-name
	"RET503", # https://docs.astral.sh/ruff/rules/implicit-return
	"T201",   # https://docs.astral.sh/ruff/rules/print
	"TRY003", # https://docs.astral.sh/ruff/rules/raise-vanilla-args
	"TRY301", # https://docs.astral.sh/ruff/rules/raise-within-try
	"TRY400", # https://docs.astral.sh/ruff/rules/error-instead-of-exception
	"TRY401", # https://docs.astral.sh/ruff/rules/verbose-log-message
]
